# Trigger the bindings project to create an issue when a new feature is added.

name: Create code bindings issue for new algorithm

on:
  pull_request:
    types: [closed]

jobs:
  create-issue:
    name: Trigger bindings issue creation
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'bindings needed')
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ISSUE_BOT_APP_ID }}
          private-key: ${{ secrets.ISSUE_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - run: |
          gh issue create --repo $ORG/issue_test --title "$ISSUE_TITLE" --body "Need bindings for PR $REPO/pull/$PR_NUMBER" --label "bindings needed" --assignee "prosilio,$PR_AUTHOR"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          ISSUE_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          ORG: ${{ github.repository_owner }}
          REPO: ${{ github.repository }}
