name: Pull request merge

on:
  merge_group:
  pull_request:

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  echo-ref:
    runs-on: ubuntu-latest
    steps:
      - name: Echo ref
        run: echo "${{github.ref}}"

      - name: Echo event number
        run: echo "refs/pull/$PR_NUMBER/merge"
  merge1:
    name: Merge1
    runs-on: ubuntu-latest
    steps:
      - name: Echo1
        if: ${{github.ref}} == "refs/pull/$PR_NUMBER/merge"}}
        run: |
          date
          echo "Merging"
  merge2:
    name: Merge2
    runs-on: ubuntu-latest
    steps:
      - name: Echo2
        if: ${{github.ref == 'refs/heads/main'}}
        run: |
          date
          echo "Merging"
