# Lightweight unit testing (compared to cibuildwheel) to quickly iterate on pull
# requests. It is recommended that you manually run the wheels.yml workflow for
# more thorough unit testing before merging the pull request.

name: Unit tests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - ".clang-format"
      - ".gitignore"
      - "LICENSE"
      - "README.MD"
      - "docs/**"

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container: ghcr.io/modcam/devcontainer:latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.21"
          enable-cache: true
          python-version: 3.9

      - name: Run unit tests
        run: >
          uv run --all-extras --dev --verbose
          --config-setting=cmake.args="--preset vcpkg"
          --config-setting=cmake.build-type="Release"
          pytest --junitxml=junit/test-results-${{ matrix.python-version }}.xml

      - name: Upload test results
        uses: actions/upload-artifact@v6
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        if: ${{ always() }}
