# The version should be updated whenever changes are made to 'main'. To update
# the version, this workflow should
# - checkout the code,
# - update the VERSION file,
# - amend the last commit to include the bumped VERSION file, and
# - tag that commit with the new version.
#
# WARNING: It's very easy to trigger an infinite workflow loop, as this workflow
# pushes to 'main', and it is itself triggered by pushes to 'main'. We avoid
# this situation with careful path filtering.

name: Update version

on:
  push:
    branches: [main]
    paths:
      - "include/**"
      - "packaging/**"
      - "src/**"
      - "!VERSION"

env:
  VERSION_FILE: VERSION

jobs:
  update-version:
    name: Update version
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Update version
        run: cmake -P ./cmake/update_version.cmake

      - name: Commit new version
        run: |
          git config user.name 'modcam-version-update[bot]'
          git config user.email '199305358+modcam-version-update[bot]@users.noreply.github.com'
          version="$(< $VERSION_FILE)"
          echo "New version: $version"
          git add $VERSION_FILE
          git commit --amend --no-edit
          git tag -a $version -m "$version"
          git push origin main --follow-tags --force
